
import logging

from sqlalchemy import text

from llm.embeddings import get_dimension

from .schemas import EntityType, VectorMetadata
from .utils import vector_session

logger = logging.getLogger(__name__)


def _existing_dimension(session) -> int | None:
    """
    Reads the width of the embedding column, or None if the table does not
    exist yet. pgvector records it in atttypmod.
    """
    row = session.execute(text("""
        SELECT a.atttypmod AS dim
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        WHERE c.relname = 'knowledge_vectors'
          AND a.attname = 'embedding'
          AND a.attnum > 0
          AND NOT a.attisdropped
    """)).first()

    if not row or row.dim is None or row.dim < 0:
        return None

    return int(row.dim)


def ensure_vector_table() -> None:
    """
    Ensures the vector extension and knowledge_vectors table exist, with a
    column width matching the configured embedding model.

    If the model changed, every stored vector is now the wrong shape and each
    query would error. Vectors are derived data — regenerated by re-approving
    knowledge from the dashboard — so the table is rebuilt and the admin is
    warned loudly, rather than being left with a silently broken search.
    """
    dimension = get_dimension()

    try:
        with vector_session() as session:
            session.execute(text("CREATE EXTENSION IF NOT EXISTS vector;"))

            current = _existing_dimension(session)

            if current is not None and current != dimension:
                logger.warning(
                    "Embedding dimension changed (%s -> %s). Rebuilding "
                    "knowledge_vectors — re-approve knowledge for each service "
                    "and district from the dashboard to restore semantic search.",
                    current, dimension,
                )
                session.execute(text("DROP TABLE IF EXISTS knowledge_vectors;"))

            session.execute(text(f"""
                CREATE TABLE IF NOT EXISTS knowledge_vectors (
                    id INT NOT NULL,
                    type VARCHAR(50) NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    embedding vector({dimension}),
                    updated_at TIMESTAMP DEFAULT NOW(),
                    PRIMARY KEY (id, type)
                );
            """))

    except Exception as e:
        logger.warning("Failed to initialize vector table: %s", e)


def _to_pgvector_literal(embedding: list[float]) -> str:
    """pgvector expects a string like '[0.1,0.2,0.3]'."""
    return "[" + ",".join(str(x) for x in embedding) + "]"


def upsert_vector(metadata: VectorMetadata, embedding: list[float]) -> None:
    """
    Inserts a new embedding or updates the existing one for (id, type).
    Metadata written is strictly {id, type, name} per spec.
    """
    vector_literal = _to_pgvector_literal(embedding)

    with vector_session() as session:
        session.execute(
            text("""
                INSERT INTO knowledge_vectors (id, type, name, embedding, updated_at)
                VALUES (:id, :type, :name, CAST(:embedding AS vector), now())
                ON CONFLICT (id, type)
                DO UPDATE SET
                    name = EXCLUDED.name,
                    embedding = EXCLUDED.embedding,
                    updated_at = now()
            """),
            {
                "id": metadata.id,
                "type": metadata.type.value,
                "name": metadata.name,
                "embedding": vector_literal,
            },
        )
    logger.info("Upserted vector for %s id=%s", metadata.type.value, metadata.id)


def delete_vector(entity_id: int, entity_type: EntityType) -> None:
    """Removes a vector, e.g. if the service or district is deleted."""
    with vector_session() as session:
        session.execute(
            text("DELETE FROM knowledge_vectors WHERE id = :id AND type = :type"),
            {"id": entity_id, "type": entity_type.value},
        )
    logger.info("Deleted vector for %s id=%s", entity_type.value, entity_id)